### PR TITLE
Some small fixes and improvements, update dependencies

### LINKED ISSUE #67: Poor error message when running as non-root
I attempted to initialize a new Beegfs node running as a regular user:

 (15:48:16) test:/data/Code/beegfs/rpms $ /opt/beegfs/sbin/beegfs-mgmtd --init
Creating database file "/var/lib/beegfs/mgmtd.sqlite" failed: unable to open database file: /var/lib/beegfs/mgmtd.sqlite: Error code 14: unable to open database file
Error: 1

The (correct) way to do this is to run it as root, but if you miss this fact then the error message is deeply unhelpful.

One possible fix would be to have beegfs-mgmtd give an error message saying "This command must be run as root".

### LINKED ISSUE #70: Missing unit for quota timeout example in the .toml file
The sample text for the quota timeout is "30"; it should instead say something like "30s"

### PR DESCRIPTION
**Pull request by rustybee42**
See commits.

Closes #67, #70

### CODE REVIEW

File: mgmtd/src/main.rs [hunk 1]
```diff
@@ -197,6 +193,7 @@ fn init_db(db_file: &Path, v7_path: Option<&Path>, fs_uuid: Option<Uuid>) -> Res
                 .parent()
                 .ok_or_else(|| anyhow!("File does not have a parent folder"))?,
         )?;
+        std::fs::File::create_new(db_file)?;
         conn.backup(rusqlite::MAIN_DB, db_file, None)?;
```
Comment (iamjoemccormick) [inline mgmtd/src/main.rs]: nitpick: if `conn.backup` fails we leave an orphaned empty file that would require the user to manually cleanup before they could run `--init` again. It would be nice to cleanup on error.

That said I'm not really worried about it, most likely an error from `conn.backup()` probably indicates I/O or file system errors (e.g., disk full), which are fairly unlikely if we were just able to create the file.

**Review by iamjoemccormick — DISMISSED** [review]

**Comment by rustybee42** [comment]
I now also updated all the dependencies to get rid of the security advisory and also improved/fixed some of the config descriptions.

File: mgmtd/src/main.rs (hunk 1 above)
Comment (rustybee42) [reply mgmtd/src/main.rs]: Yeah, that's right. Not a big deal, but added it anyway as I couldn't merge the PR without resolving  the security advisory.

Comment (iamjoemccormick) [reply mgmtd/src/main.rs]: As written if a user reruns `beegfs-mgmtd --init` after the DB was created/populated, we would return `AlreadyExists` but then delete the existing database.

We need to move the cleanup so it only fires after `create_new` has succeeded, only if `conn.backup` specifically fails.

File: mgmtd/src/main.rs [hunk 2]
```diff
@@ -197,11 +193,15 @@ fn init_db(db_file: &Path, v7_path: Option<&Path>, fs_uuid: Option<Uuid>) -> Res
...
 
         Ok(())
     })()
-    .with_context(|| format!("Creating database file {db_file:?} failed"))?;
+    .with_context(|| format!("Creating database file {db_file:?} failed"))
+    .inspect_err(|_| {
+        std::fs::remove_file(db_file).ok();
```
Comment (iamjoemccormick) [inline mgmtd/src/main.rs]: nitpick: could warn here if for some reason we failed to cleanup instead of silently swallowing the cleanup error.

**Review by iamjoemccormick — CHANGES_REQUESTED** [review]

File: mgmtd/src/main.rs (hunk 1 above)
Comment (rustybee42) [reply mgmtd/src/main.rs]: Good catch, fixed

File: mgmtd/src/main.rs [hunk 3]
```diff
@@ -154,7 +154,7 @@ If you want to initialize a new system, refer to --help or doc.beegfs.io.",
 
         // Mgmtds systemd unit is set to service type "notify". Here we send out the
         // notification that the service has completed startup and is ready for serving
-        let _ = sd_notify::notify(true, &[sd_notify::NotifyState::Ready]);
+        let _ = sd_notify::notify(&[sd_notify::NotifyState::Ready]);
```
Comment (iamjoemccormick) [inline mgmtd/src/main.rs:157]: thought: Claude review flagged: 

> The old call was `sd_notify::notify(true, &[Ready])` where true meant "unset NOTIFY_SOCKET etc. after sending". In 0.5.0 that parameter is gone and unsetting is a separate unset_env_vars() call. Result: the env vars now persist in mgmtd's environment. For a daemon that doesn't spawn children with inherited env this is harmless, but if anything ever execs a subprocess that itself tries to talk to systemd, it could send a stray READY=1. Probably fine here, but worth a conscious decision rather than an accidental drop.

I had already looked into what `true` was originally doing for us and thought dropping it was fine. I presume if we spawn children with inherited environment there will be other implications to consider anyway.

**Review by iamjoemccormick — APPROVED** [review]

File: mgmtd/src/main.rs (hunk 3 above)
Comment (rustybee42) [reply mgmtd/src/main.rs:157]: We will most likely never do this anyway
